services:
  # --- Reverse Proxy ---
  nginx:
    image: nginx:alpine
    container_name: harbor-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - harbor-network

  # --- Application ---
  frontend:
    build: ./frontend
    container_name: harbor-frontend
    networks:
      - harbor-network
  backend:
    build: ./backend
    container_name: harbor-backend
    volumes:
      - /home/ubuntu/.ssh:/home/ubuntu/.ssh:rw  # <--- Does it have this?
    networks:
      - harbor-network
networks:
  harbor-network:
    driver: bridge
