---
- name: Restart SSH
  service:
    name: ssh
    state: restarted
  become: yes

- name: Reload Systemd
  systemd:
    daemon_reload: yes
  become: yes

- name: Restart HCIP Service
  systemd:
    name: galera-hcip
    state: restarted
  become: yes
