all:
  children:
    async:
      hosts:
        async-node:
          ansible_host: 192.168.64.7
          server_id: 16391
    galera:
      hosts:
        db-node-01:
          ansible_host: 192.168.64.2
          server_id: 16386
        db-node-02:
          ansible_host: 192.168.64.3
          server_id: 16387
        db-node-03:
          ansible_host: 192.168.64.4
          server_id: 16388
    lvs:
      hosts:
        lvs-node-1:
          ansible_host: 192.168.64.5
        lvs-node-2:
          ansible_host: 192.168.64.6
    monitoring:
      hosts:
        monitor-node:
          ansible_host: 192.168.64.8
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ansible
    ansible_user: ubuntu
