all:
  children:
    async:
      hosts:
        async-node:
          ansible_host: 192.168.64.5
          server_id: 16389
    galera:
      hosts:
        db-node-01:
          ansible_host: 192.168.64.7
          server_id: 16391
        db-node-02:
          ansible_host: 192.168.64.8
          server_id: 16392
        db-node-03:
          ansible_host: 192.168.64.9
          server_id: 16393
    lvs:
      hosts:
        lvs-node-1:
          ansible_host: 192.168.64.3
        lvs-node-2:
          ansible_host: 192.168.64.4
    monitoring:
      hosts:
        monitor-node:
          ansible_host: 192.168.64.6
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ansible
    ansible_user: ubuntu
