all:
  children:
    async:
      hosts:
        async-node:
          ansible_host: 192.168.64.222
          server_id: 16606
    galera:
      hosts:
        db-node-01:
          ansible_host: 192.168.64.217
          server_id: 16601
        db-node-02:
          ansible_host: 192.168.64.218
          server_id: 16602
        db-node-03:
          ansible_host: 192.168.64.219
          server_id: 16603
    lvs:
      hosts:
        lvs-node-1:
          ansible_host: 192.168.64.220
        lvs-node-2:
          ansible_host: 192.168.64.221
    monitoring:
      hosts:
        monitor-node:
          ansible_host: 192.168.64.223
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ansible
    ansible_user: ubuntu
