all:
  children:
    async:
      hosts:
        async-node:
          ansible_host: 192.168.64.199
          server_id: 16583
    galera:
      hosts:
        db-node-01:
          ansible_host: 192.168.64.192
          server_id: 16576
        db-node-02:
          ansible_host: 192.168.64.193
          server_id: 16577
        db-node-03:
          ansible_host: 192.168.64.194
          server_id: 16578
    lvs:
      hosts:
        lvs-node-1:
          ansible_host: 192.168.64.196
        lvs-node-2:
          ansible_host: 192.168.64.197
    monitoring:
      hosts:
        monitor-node:
          ansible_host: 192.168.64.201
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ansible
    ansible_user: ubuntu
