all:
  children:
    async:
      hosts:
        async-node:
          ansible_host: 192.168.64.207
          server_id: 16591
    galera:
      hosts:
        db-node-01:
          ansible_host: 192.168.64.202
          server_id: 16586
        db-node-02:
          ansible_host: 192.168.64.203
          server_id: 16587
        db-node-03:
          ansible_host: 192.168.64.204
          server_id: 16588
    lvs:
      hosts:
        lvs-node-1:
          ansible_host: 192.168.64.205
        lvs-node-2:
          ansible_host: 192.168.64.206
    monitoring:
      hosts:
        monitor-node:
          ansible_host: 192.168.64.209
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ansible
    ansible_user: ubuntu
