all:
  children:
    async:
      hosts:
        async-node:
          ansible_host: 192.168.64.236
          server_id: 16620
    galera:
      hosts:
        db-node-01:
          ansible_host: 192.168.64.232
          server_id: 16616
        db-node-02:
          ansible_host: 192.168.64.233
          server_id: 16617
        db-node-03:
          ansible_host: 192.168.64.234
          server_id: 16618
    lvs:
      hosts:
        lvs-node-1:
          ansible_host: 192.168.64.237
        lvs-node-2:
          ansible_host: 192.168.64.238
    monitoring:
      hosts:
        monitor-node:
          ansible_host: 192.168.64.235
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ansible
    ansible_user: ubuntu
