all:
  children:
    async:
      hosts:
        async-node:
          ansible_host: 192.168.64.215
          server_id: 16599
    galera:
      hosts:
        db-node-01:
          ansible_host: 192.168.64.210
          server_id: 16594
        db-node-02:
          ansible_host: 192.168.64.211
          server_id: 16595
        db-node-03:
          ansible_host: 192.168.64.212
          server_id: 16596
    lvs:
      hosts:
        lvs-node-1:
          ansible_host: 192.168.64.213
        lvs-node-2:
          ansible_host: 192.168.64.214
    monitoring:
      hosts:
        monitor-node:
          ansible_host: 192.168.64.216
  vars:
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ansible_ssh_private_key_file: /home/ubuntu/.ssh/id_ansible
    ansible_user: ubuntu
